### ISSUE TITLE
Cross-platform builds may not be working as expected

### ISSUE THREAD

**Issue by scottslowe** [pulumi/zephyr-app#11]
### What happened?

The addition of the `awsx.ecr.Image` resource creates a dependency on a local Docker instance, and for Apple Silicon-based Mac users will try to build ARM64 images. These ARM64 images will fail to deploy correctly because the EKS cluster is using AMD64 nodes.

### Expected Behavior

I expected AMD64 images to be built.

### Steps to reproduce

Run `pulumi up` on an Apple Silicon-based Mac running Docker Desktop. The UI deployment will eventually fail, and inspecting the local Docker image will show that it is an ARM64 image.

### Output of `pulumi about`

N/A

### Additional context

Modifying the `awsx.ecr.Image` resource in this way _should_ work, but it doesn't seem to work correctly on my Mac:
```typescript
const uiImage = new awsx.ecr.Image("ui-image", {
    repositoryUrl: repository.url,
    dockerfile: "../images/java17/Dockerfile",
    path: "../src/ui",
    args: {
        JAR_PATH: "target/ui-0.0.1-SNAPSHOT.jar",
    },
    env: {
        DOCKER_BUILDKIT: "1",
        DOCKER_DEFAULT_PLATFORM: "linux/amd64"
    }
});
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
@scottslowe do you need a triage on this? if not, do you mind dropping the needs triage label?

**Comment by scottslowe** [comment]
Closing this issue. Testing with earlier branches shows that the Pulumi program is configured to build `linux/amd64` images, and this works even from an Apple Silicon-based Mac.
