### ISSUE TITLE
A few things to document

### ISSUE THREAD

**Issue by cnunciato** [pulumi/zephyr-app#4]
Some notes as I've started working with Zephyr myself:

* We should add some instructions to the readme as to how to deploy this -- the usual stuff: `pulumi new`, `pulumi stack init`, set whatever configs are necessary, `up`, etc., such that someone scanning the README would be able to pick it up and start working with it. Bonus points for a template and Deploy with Pulumi button.
* We should explain what to do after the deployment completes. Where can I see the running app? How do I interact with the cluster? Etc.
* What's the dev workflow around the app itself? For example, How do I make changes to the web UI, or the infra, and redeploy?
* What are the various repo directories for (`develop`, `deploy`, etc.)?
* We should link to the blog post series from the README as well.

**Comment by scottslowe** [comment]
I'm going to go ahead and close this. Everything listed above is documented _except_ for the development workflow and some notes around the `develop` and `deploy` folders.
