### ISSUE TITLE
Add some Issue automation

### ISSUE THREAD

**Issue by cnunciato** [pulumi/zephyr-app#5]
We should have issues posted on this repo dropped onto the Developer Relations board for triage -- for example, as we do with [templates](https://github.com/pulumi/templates/blob/master/.github/workflows/add-to-project.yml) and [examples](https://github.com/pulumi/examples/blob/master/.github/workflows/add-to-project.yaml).

**Comment by scottslowe** [comment]
Fixed for zephyr-infra via https://github.com/pulumi/zephyr-infra/pull/1
Fixed for zephyr-k8s via https://github.com/pulumi/zephyr-k8s/pull/2
Fixed for zephyr-app via https://github.com/pulumi/zephyr-app/pull/27
